"use client";
import { useState } from "react";

type ClassificationResult = { classificacao:string; ncm:string; confianca:number; descricaoAduaneira:string; justificativa:string; informacoesPendentes:string };
const bases = [["Brasil","NCM, NESH e RFB","Prioritária"],["Internacional","OMA, UE, EUA, Canadá e Japão","Comparativa"],["Contencioso","CARF e precedentes","Complementar"]];

export default function Home() {
  const [loading,setLoading]=useState(false); const [files,setFiles]=useState<File[]>([]);
  const [result,setResult]=useState<ClassificationResult|null>(null); const [error,setError]=useState("");
  const analisar=async()=>{setLoading(true);setError("");setResult(null);try{const form=new FormData();form.append("descricao",(document.getElementById("descricao") as HTMLTextAreaElement)?.value||"");files.forEach(file=>form.append("documentos",file));const response=await fetch("/api/classificar",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||"Não foi possível concluir a análise.");setResult(data.result)}catch(problem){setError(problem instanceof Error?problem.message:"Erro inesperado.")}finally{setLoading(false)}};
  const adicionar=(list:FileList|null)=>{if(!list)return;setFiles(current=>[...current,...Array.from(list).filter(file=>!current.some(item=>item.name===file.name&&item.size===file.size))])};
  const tamanho=(bytes:number)=>bytes<1024*1024?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/1024/1024).toFixed(1)} MB`;
  return <main>
    <header className="topbar"><div className="brand"><img src="/grupo-portorium.png" alt="Grupo Portorium"/></div><div className="productName"><span>Classificador</span> Vetorial</div><button className="user" aria-label="Usuário">WT</button></header>
    <section className="workspace">
      <aside className="sidebar"><button className="newAnalysis" onClick={()=>{setResult(null);setError("")}}>＋ Nova análise</button><nav><a className="active">⌕ Analisar mercadoria</a></nav><div className="sourceTitle">BASES CONSULTADAS</div>{bases.map(([country,detail,kind])=><div className="source" key={country}><span className="sourceDot"/><div><strong>{country}</strong><small>{detail}</small><em>{kind}</em></div></div>)}<div className="security"><span>◆</span><p><strong>Arquitetura RAG controlada</strong>Consulta orientada por bases vetoriais selecionadas, com chave protegida no servidor e revisão humana indispensável.</p></div></aside>
      <div className="content">
        <div className="intro"><div><span className="eyebrow">TECNOLOGIA PORTORIUM PARA CLASSIFICAÇÃO FISCAL</span><h1>Identifique. Fundamente.<br/><i>Decida com segurança.</i></h1></div><div className="architectureSeal"><span>◆</span><div><strong>RAG + base vetorial curada</strong><small>Respostas ancoradas em fontes selecionadas</small></div></div></div>
        <section className="protectionPanel"><div><span>01</span><p><strong>Dados protegidos</strong>A chave permanece no servidor. Dados enviados pela API não são usados para treinar modelos da OpenAI por padrão.</p></div><div><span>02</span><p><strong>Conhecimento delimitado</strong>A recuperação aumentada por contexto (RAG) prioriza a base vetorial especializada antes da resposta.</p></div><div><span>03</span><p><strong>Controle de alucinações</strong>Fontes selecionadas, saída estruturada e validação humana reduzem — mas não eliminam — respostas incorretas.</p></div></section>
        <section className="inputCard"><label>Descreva a mercadoria ou cole as informações técnicas</label><textarea id="descricao" placeholder="Ex.: nome técnico, composição, função, funcionamento, marca, modelo e demais características conhecidas."/><input id="documentos" className="fileInput" type="file" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.md,.png,.jpg,.jpeg,.webp" onChange={event=>{adicionar(event.target.files);event.target.value=""}}/>{files.length>0&&<div className="fileList"><div className="fileSummary"><strong>{files.length} {files.length===1?"documento selecionado":"documentos selecionados"}</strong><span>Prontos para análise</span></div>{files.map((file,index)=><div className="fileItem" key={`${file.name}-${file.size}`}><span className="fileIcon">▤</span><p><strong>{file.name}</strong><small>{tamanho(file.size)}</small></p><button aria-label={`Remover ${file.name}`} onClick={()=>setFiles(current=>current.filter((_,position)=>position!==index))}>×</button></div>)}</div>}<div className="inputFooter"><label htmlFor="documentos" className="attach">＋ Anexar documentos</label><span>PDF, Word, Excel, texto ou imagens</span><button className="analyze" onClick={analisar} disabled={loading}>{loading?"Consultando bases…":files.length?`Analisar com ${files.length} ${files.length===1?"anexo":"anexos"} →`:"Analisar mercadoria →"}</button></div></section>
        {error&&<div className="apiError"><strong>Não foi possível concluir</strong><span>{error}</span></div>}
        {result?<section className="resultArea"><div className="resultTitle"><div><span className="tag">RESULTADO DA PESQUISA VETORIAL</span><h2>Análise técnica assistida</h2></div><div className="score"><span>CONFIANÇA ESTIMADA</span><strong>{result.confianca}%</strong><div><i style={{width:`${result.confianca}%`}}/></div><small>Indicador do modelo, não garantia de acerto</small></div></div><div className="resultGrid"><article className="answerCard classificationCard"><span className="cardNumber">01</span><div className="cardLabel">SUGESTÃO DE CLASSIFICAÇÃO</div><div className="ncm">{result.ncm||"NCM não determinada"}</div><p>{result.classificacao}</p></article><article className="answerCard"><span className="cardNumber">02</span><div className="cardLabel">DESCRIÇÃO ADUANEIRA · CATÁLOGO DE PRODUTOS</div><p>{result.descricaoAduaneira}</p></article><article className="answerCard"><span className="cardNumber">03</span><div className="cardLabel">JUSTIFICATIVA DA CLASSIFICAÇÃO</div><p>{result.justificativa}</p>{result.informacoesPendentes&&<div className="pending"><strong>Informações pendentes</strong>{result.informacoesPendentes}</div>}</article></div></section>:<section className="emptyResult"><span>⌕</span><h3>Aguardando uma mercadoria</h3><p>Informe as características ou anexe os documentos para iniciar a pesquisa nas bases de classificação fiscal.</p></section>}
        <section className="legalDisclaimer"><span>!</span><div><strong>Aviso jurídico sobre a classificação indicada</strong><p>Este resultado é uma indicação técnica assistida e não constitui decisão da administração tributária, parecer jurídico ou garantia de enquadramento fiscal. Para obter manifestação formal da Receita Federal do Brasil sobre a classificação de uma mercadoria específica, deve ser apresentada consulta nos termos da <b>Instrução Normativa RFB nº 2.057, de 9 de dezembro de 2021</b>. A proteção jurídica depende de consulta eficaz, formulada com observância de todos os requisitos normativos, e cada processo deve referir-se a um único produto.</p></div></section>
        <footer>Classificador Vetorial Portorium · Tecnologia aplicada à conformidade aduaneira <span>Análise assistida</span></footer>
      </div>
    </section>
  </main>
}
